[profile.default]
src = "src"
libs = ["lib"]
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
bytecode_hash = "none"
fs_permissions = [{ access = "read", path = "../config" }, { access = "read-write", path = "../deployments" }]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/","forge-std/=lib/forge-std/src/","infinity-core/=lib/infinity-core/","infinity-periphery/=lib/infinity-periphery/","permit2/=lib/permit2/","solmate/=lib/solmate/"]

[rpc_endpoints]
bsc = "${BSC_RPC}"
